my_site/urls.py
from django.contrib import admin
from django.urls import path
from p_library import views
# from p_library.urls import urlpatterns as library_urls
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('index/', views.index),
    path('index/book_increment/', views.book_increment),
    path('index/book_decrement/', views.book_decrement),
    path('redaction/', views.redaction, name='redaction'),
    path('', include('p_library.urls', namespace='p_library')),
    path('rent/', views.rent, name='rent'),
    path('rent/rent_delete/', views.rent_delete),

    # тестовые 
    # path("<str:name>/", views.PublisherDetailView.as_view(), name="publisher-detail"),
    path('contact/', views.ContactView.as_view()),

    # тестовые AuthorCreate, AuthorUpdate, AuthorDelete
    path('test/author-create/', views.AuthorCreate.as_view()),
    path('test/author-update/', views.AuthorUpdate.as_view()),
    path('test/author-delete/', views.AuthorDelete.as_view()),


]

# urlpatterns += library_urls

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

p_library/urls.py
from django.contrib import admin
from django.urls import path  
from .views import AuthorEdit, AuthorList, author_create_many, books_author_create_many, create_friend, rent_edit, AuthorPageView, PublisherList

app_name = 'p_library'  
urlpatterns = [
    path('author/create', AuthorEdit.as_view(), name='author_create'),
    path('authors', AuthorList.as_view(), name='author_list'),
    path('author/create_many', author_create_many, name='author_create_many'),
    path('author_book/create_many', books_author_create_many, name='author_book_create_many'),
    path('create/friend', create_friend, name='create_friend'),
    path('create/rent', rent_edit, name='rent_create'),
    path('authors_list_test', AuthorPageView.as_view(template_name = "authors.html"), name='authors_list_test'),
    path("publishers", PublisherList.as_view(template_name = 'publishers.html'), name='publishers'),
    # path("<str:name>/", PublisherDetailView.as_view(), name="publisher-detail"),
]

p_library/models.py
from django.db import models
import uuid
from p_library.validators import validate_zero
from django.urls import reverse_lazy, reverse



# Create your models here.

class Author(models.Model):  
    full_name = models.TextField()  
    birth_year = models.SmallIntegerField()  
    country = models.CharField(max_length=2)
    
    def __str__(self):
        return self.full_name

    def get_absolute_url(self):
        return reverse('author-detail', kwargs={'pk': self.pk}) 

class Redaction(models.Model):
    # id = models.UUIDField(primary_key=True, default=uuid.uuid4,editable=False, verbose_name="UUID")
    name = models.TextField()
    city = models.CharField(max_length=60)

    def __str__(self):
        return self.name

class Friend(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name

class Publisher(models.Model):
    name = models.CharField(max_length=30)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=60)
    state_province = models.CharField(max_length=30)
    country = models.CharField(max_length=50)
    website = models.URLField()

    def __str__(self):
        return self.name
	
class Book(models.Model):  
    ISBN = models.CharField(max_length=13)  
    title = models.TextField()  
    description = models.TextField()  
    year_release = models.SmallIntegerField()  
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    copy_count = models.SmallIntegerField(default=2)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    cover = models.ImageField(upload_to="covers/%Y/%m/%d", blank=True)
    redact = models.ForeignKey(Redaction,on_delete=models.SET_NULL, related_name='books', blank=True, null=True)
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE)
    friends = models.ManyToManyField(Friend, blank=True, through='Rent', related_name='friendrent')

    def __str__(self):
        return self.title

class Rent(models.Model):
    friend = models.ForeignKey(Friend, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    count = models.SmallIntegerField()

    def save(self, *args, **kwargs):
        from django.http import HttpResponseServerError
        from p_library.models import Book
        book = Book.objects.get(id=self.book.id)
        book.copy_count -= self.count
        book.save()
        super(Rent, self).save(*args, **kwargs)

p_library/forms.py
from django import forms  
from p_library.models import Author, Book, Friend, Rent
from django.forms import formset_factory
from p_library.validators import validate_zero
  
class AuthorForm(forms.ModelForm):  

    full_name = forms.CharField(widget=forms.TextInput)
    
    class Meta:  
        model = Author  
        fields = '__all__'

class BookForm(forms.ModelForm):
    copy_count = forms.IntegerField(validators=[validate_zero])
    class Meta:
        model = Book
        fields = "__all__"

class FriendForm(forms.ModelForm):
    class Meta:
        model = Friend
        fields = "__all__"

class RentForm(forms.ModelForm):
    class Meta:
        model = Rent
        fields = "__all__"

class ContactForm(forms.Form):
    name = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)

    def send_email(self):
        # send email using the self.cleaned_data dictionary
        pass

p_library/views.py
import json

from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template import loader
from django.views.generic import CreateView, DeleteView, UpdateView, ListView, View 
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import FormView
from django.utils import timezone
from django.urls import reverse_lazy, reverse
from django.forms import formset_factory  
from django.http.response import HttpResponseRedirect
from django.http import HttpResponseServerError
from .models import Book, Redaction, Author, Rent, Friend, Publisher
from p_library.forms import AuthorForm, BookForm, FriendForm, RentForm, ContactForm

# Create your views here.

def books_list(request):
	books = Book.objects.all()
	return HttpResponse(books)

def index(request):
	template = loader.get_template('index.html')
	books = Book.objects.all()
	biblio_data = {
		"title": "мою библиотеку", 
		"books": books,
	}
	return HttpResponse(template.render(biblio_data, request))


def book_increment(request):
    if request.method == 'POST':
        book_id = request.POST['id']
        if not book_id:
            return redirect('/index/')
        else:
            book = Book.objects.filter(id=book_id).first()
            if not book:
                return redirect('/index/')
            book.copy_count += 1
            book.save()
        return redirect('/index/')
    else:
        return redirect('/index/')


def book_decrement(request):
    if request.method == 'POST':
        book_id = request.POST['id']
        if not book_id:
            return redirect('/index/')
        else:
            book = Book.objects.filter(id=book_id).first()
            if not book:
                return redirect('/index/')
            if book.copy_count < 1:
                book.copy_count = 0
            else:
                book.copy_count -= 1
            book.save()
        return redirect('/index/')
    else:
        return redirect('/index/')


def redaction(request):
    template = loader.get_template('redaction.html')
    # books = Book.objects.all()
    redact = Redaction.objects.all()
    data_ = {
        "redact": redact,
    }
    return HttpResponse(template.render(data_, request))

class AuthorEdit(CreateView):  
    model = Author  
    form_class = AuthorForm  
    success_url = reverse_lazy('p_library:author_list')  
    template_name = 'author_edit.html'  
  
  
class AuthorList(ListView):  
    model = Author  
    template_name = 'author_list.html'

def author_create_many(request):  
    AuthorFormSet = formset_factory(AuthorForm, extra=2)  #  Первым делом, получим класс, который будет создавать наши формы. Обратите внимание на параметр `extra`, в данном случае он равен двум, это значит, что на странице с несколькими формами изначально будет появляться 2 формы создания авторов.
    if request.method == 'POST':  #  Наш обработчик будет обрабатывать и GET и POST запросы. POST запрос будет содержать в себе уже заполненные данные формы
        author_formset = AuthorFormSet(request.POST, request.FILES, prefix='authors')  #  Здесь мы заполняем формы формсета теми данными, которые пришли в запросе. Обратите внимание на параметр `prefix`. Мы можем иметь на странице не только несколько форм, но и разных формсетов, этот параметр позволяет их отличать в запросе.
        if author_formset.is_valid():  #  Проверяем, валидны ли данные формы
            for author_form in author_formset:  
                author_form.save()  #  Сохраним каждую форму в формсете
            return HttpResponseRedirect(reverse_lazy('p_library:author_list'))  #  После чего, переадресуем браузер на список всех авторов.
    else:  #  Если обработчик получил GET запрос, значит в ответ нужно просто "нарисовать" формы.
        author_formset = AuthorFormSet(prefix='authors')  #  Инициализируем формсет и ниже передаём его в контекст шаблона.
    return render(request, 'manage_authors.html', {'author_formset': author_formset})

def books_author_create_many(request):
    AuthorFormSet = formset_factory(AuthorForm, extra=2)
    BookFormSet = formset_factory(BookForm, extra=2)

    if request.method == 'POST':
        author_formset = AuthorFormSet(request.POST, request.FILES, prefix='author')
        book_formset = BookFormSet(request.POST, request.FILES, prefix='books')
        if author_formset.is_valid() and book_formset.is_valid():
            for author_form in author_formset:
                author_form.save()
            for book_form in book_formset:
                book_form.save()
            return HttpResponseRedirect(reverse_lazy('p_library:author_list'))
    else:
        author_formset = AuthorFormSet(prefix='author')
        book_formset = BookFormSet(prefix='books')
    return render(request, 'manage_books_authors.html', {'author_formset': author_formset, 'book_formset': book_formset})

def rent(request):
    rents = Rent.objects.all()
    books = Book.objects.all()
    return render(request, 'rent.html', {'rents': rents, 'books': books})

def create_friend(request):
    if request.method != 'POST':
        new_friend = FriendForm()
    else:
        new_friend = FriendForm(data=request.POST)
        if new_friend.is_valid():
            new_friend.save()
            return HttpResponseRedirect(reverse('rent'))

    context = {'new_friend': new_friend}
    return render(request, 'create_friend.html', context)

def rent_edit(request):
    if request.method != 'POST':
        new_rent = RentForm()
    else:
        new_rent = RentForm(data=request.POST)
        rent_id = request.POST['book']
        book = Book.objects.get(id=rent_id)
        if new_rent.is_valid():
            new_rent = new_rent.save(commit=False)
            book.copy_count -= new_rent.count
            if book.copy_count < 0:
                return HttpResponseServerError('В библиотеке нет такого количества копий данной книги')   
            else:        
                new_rent.save()
                return HttpResponseRedirect(reverse('rent'))

    context = {'new_rent': new_rent}
    return render(request, 'rent_edit.html', context)

    
def rent_delete(request):
    if request.method == 'POST':
        rent_id = request.POST['id']
        if not rent_id:
            return redirect('/rent/')
        else:
            rent = Rent.objects.filter(id=rent_id).first()
            book = Book.objects.get(id=rent.book.id)
            if not rent:
                return redirect('/rent/')
            book.copy_count +=rent.count
            book.save()
            rent.delete()
        return redirect('/rent/')
    else:
        return redirect('/rent/')

class AuthorPageView(TemplateView):

    template_name = "authors.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["authors"] = Author.objects.all()
        return context

class PublisherList(ListView):
    model = Publisher
    # queryset = Publisher.objects.filter(country="Russia") # Позволяет задать фильтры для чтения данных из БД.
    template_name = 'publishers.html' # Название шаблона

    # context_object_name = "publishers" # Позволяет задать имя переменной, в которой хранится список объектов для отображения
    
    # paginate_by = 50 # Для создания постраничного вывода данных некоторой модели предусмотрен атрибут paginate_by. В нём указывается количество элементов списка, которое сервер будет выводить.
        
        # def get_queryset(self): # Метод get_queryset предназначен для выполнения тонкой фильтрации данных на каждый запрос. Например, мы можем использовать авторизационные данные пользователя для фильтрации и сортировки данных. Предположим, что при регистрации на нашем ресурсе пользователи указывают полный адрес своего проживания. Тогда мы можем ограничить список издательств только теми, которые находятся в одном городе с пользователем.
        # user_city = self.request.user.city
        # return Publisher.objects.filter(city=user_city)

# class PublisherList(View):
#     model = Publisher
    
#     def get(self):
#         publishers_list = self.model.objects.all()
#         return publishers_list
    
#     def put(self, request):
#         data = json.loads(request.body)
#         publisher = self.model(**data)
#         publisher.save()

# class PublisherDetailView(DetailView): #DetailView позволяет отобразить данные по одному объекту внутри базы данных

#     model = Publisher
#     pk_url_kwarg = 'id'
    

#     def get_context_data(self, **kwargs):
#         context = super(PublisherDetailView).get_context_data(**kwargs)
#         context["now"] = timezone.now()
#         return context

class ContactView(FormView):
    template_name = 'contact.html'
    form_class = ContactForm
    success_url = '/index/'

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        form.send_email()
        return super(ContactView, self).form_valid(form)

# для тестов CreateView, UpdateView, DeleteView
class AuthorCreate(CreateView):
    model = Author
    fields = ['full_name', 'birth_year']
    template_name = 'test_author_create.html'

class AuthorUpdate(UpdateView):
    model = Author
    fields = ['full_name']
    template_name = 'test_author_update.html'

class AuthorDelete(DeleteView):
    model = Author
    success_url = reverse_lazy('p_library:authors')

p_library/templates/author_list.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Список авторов</title>
</head>
<body>
	<a href="{% url 'index' %}">На главную</a>
	<ul>
		{% for author in object_list %}
		    <li>{{ author.full_name }}</li>
		{% endfor %}
	</ul>
</body>
</html> 

p_library/templates/authors.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Auuthors TEST</title>
</head>
<body>
    <ul>
        {% for author in authors %}    
        <li> {{ author.full_name }} </li>
        <li> {{ author.birth_year }} </li>
        <li> {{ author.country }} </li>
        <li> <br> </li>
        {% endfor %}
    </ul>
</body>
</html>

p_library/templates/base.html
<p>
    <a href="{% url 'index' %}">На главную</a> - 
    <a href="{% url 'redaction' %}">Посмотреть редакции</a> - 
    <a href="{% url 'p_library:author_create' %}">Создать нового автора</a> -
    <a href="{% url 'p_library:author_create_many' %}">Создать несколько авторов</a> -
    <a href="{% url 'p_library:author_book_create_many' %}">Создать несколько авторов и книг</a> - 
    <a href="{% url 'rent' %}">Взяли почитать</a>
</p>
{% block content %}{% endblock content %}

<a href="{% url 'p_library:authors_list_test' %}">Тест TemplateView</a> - 
<a href="{% url 'p_library:publishers' %}">Тест ListView</a>

p_library/templates/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>qwe</title>
</head>
<body>
    <form method="post">  
        {% csrf_token %}  
        {{ form.as_p }}  
        <input type="submit" value="Сохранить">  
    </form>  
</body>
</html>

p_library/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
Добро пожаловать в {{ title }}.  <br>
Тут собрано {{ books|length }} книг из моей личной коллекции.
<link rel="stylesheet" href="{% static 'style.css' %}">
<br>
<table border="1">
	<tr>
		<th>№</th>
		<th>Название</th>
		<th>Описание</th>
		<th>Обложка</th>
		<th>Год выпуска</th>
		<th>Имя автора</th>
		<th>Количество копий</th>
	</tr>
	{% for book in books %}
	<tr>
		<td>{{ forloop.counter }}</td>
		<td>{{ book.title }}</td>
		<!-- <td>{{ book.ISBN }}</td> -->
		<td>{{ book.description }}</td>
		{% if book.cover %}
			<td><img src="{{ book.cover.url }}" alt="" style="width: 250px;"></td>
		{% else %}
			<td>У книги нет обложки</td>
		{% endif %}
		<td>{{ book.year_release }}</td>
		<td>{{ book.author.full_name }}</td>
		<!-- <td>{{ book.author.country }}</td> -->
        <td>{{ book.copy_count }}</td>
		<td>
            <form action="/index/book_increment/" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            	<input type="hidden" name="id" value="{{book.id}}" />
            	<input type="submit" value="Увеличить кол-во" />
            </form>
            <form action="/index/book_decrement/" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="hidden" name="id" value="{{book.id}}" />
                <input type="submit" value="Уменьшить кол-во" />
            </form>
        </td>
	</tr>
	{% endfor %}
</table>

<br>

<p>	
	{% load my_filters %}
	{% for i in 100|range_ %}
		{% if i|div:3 %}
  			{{ i }}
		{% endif %}	
	{% endfor %}
</p>
{% endblock content %}

p_library/templates/manage_authors.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
 <meta charset="UTF-8">  
 <title>Create multiple authors</title>  
</head>  
<body>  
<form method="post">  
	{{ author_formset.management_form }}
	{% csrf_token %}  
	{% for form in author_formset %}  
		{{ form.as_ul }}  
		<br>  
	{% endfor %}
    <input type="submit" value="Сохранить"/>  
</form>  
</body>  
</html>

p_library/templates/manage_books_authors.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
 <meta charset="UTF-8">  
 <title>Create multiple Authors and Books</title>  
</head>  
<body>  
<form method="post">  
  {{ author_formset.management_form }}
  {{ book_formset.management_form }}
  {% csrf_token %}  
  {% for form in author_formset %}  
        {{ form.as_ul }}  
        <br>  
  {% endfor %}  
  
    {% for form in book_formset %}  
        {{ form.as_ul }}  
        <br>  
  {% endfor %}  
    <input type="submit" value="Сохранить"/>  
</form>  
</body>  
</html>

p_library/templates/publisher_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>test DetailView</title>
</head>
<body>
    <h1>{{ object.name }}</h1>
    <p>{{ object.website }}</p>
    <p>City: {{ object.city }}</p>
    <p>Address: {{ object.address }}</p>
    <p>Date: {{ now|date }}</p>
</body>
</html>

p_library/templates/publishers.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Список авторов</title>
</head>
<body>
	<a href="{% url 'index' %}">На главную</a>
	<ul>
		{% for publisher in object_list %}
            <li>{{ publisher.name }}</li>
            <p>{{ publisher.address }}</p>
            <p>{{ publisher.city }}</p>
            <p>{{ publisher.state_province }}</p>
		{% endfor %}
	</ul>
</body>
</html> 

p_library/templates/redaction.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Title</title>
</head>
<body>
    {% for red in redact %}
        <ul class="list-group">
            <li class="list-group-item">
                {{ red.name }}
                <ul class="list-group">
                    {% for book in red.books.all %}
                        <li class="list-group-item list-group-item-action list-group-item-success"> {{ book.title }}</li>
                    {% endfor %}
                </ul>
            </li>
        </ul>
    {% endfor %}
</body>
</html>
{% endblock content %}

p_library/templates/rent.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Rent</title>
    <!-- <link rel="stylesheet" href="{% static 'style_ind_test.css' %}"> -->
</head>
<body>

    <a href="{% url 'p_library:create_friend' %}">Добавить друга</a> - 
    <a href="{% url 'p_library:rent_create' %}">Дать книгу в аренду</a>
    <br/>
    <p>Друзья взявшие почитать книги:</p>
    <table border='1'>
        
        <tr>
            <th>№</th>
            <th>Имя друга</th>
            <th>Название книги</th>
            <th>Количество</th>
        </tr>
        {% for rent in rents %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ rent.friend }}</td>
            <td>{{ rent.book }}</td>
            <td>{{ rent.count }}</td>
            <td>
                <form action="/rent/rent_delete/" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                     <input type="hidden" name="id" value="{{rent.id}}" />
                    <input type="submit" value="Вернул книгу" />
                </form>

            </td>
        </tr>
        {% endfor %}
    </table>

    <p>Осталось копий книг:</p>
<table border='1'>
    <tr>
        <th>№</th>
        <th>Название книги</th>
        <th>Автор</th>
        <th>Количество копий</th>
    </tr>
	{% for book in books %}
	<tr>
		<td>{{ forloop.counter }}</td>
		<td>{{ book.title }}</td>
		<td>{{ book.author.full_name }}</td>
        <td>{{ book.copy_count }}</td>
	</tr>
	{% endfor %}
</table>
</body>
</html>
{% endblock content %}

p_library/templates/rent_edit.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
	<meta charset="UTF-8">  
	<title>Форма создания новой аренды</title>  
</head>  
<body>  
<form method="post">  
	{% csrf_token %}  
	{{ new_rent.as_p }}  
	<input type="submit" value="Сохранить">  
</form>  
</body>  
</html>

p_library/templates/test_author_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>TESTcreateauth</title>
</head>
<body>
    <form method="post">  
        {% csrf_token %}  
        {{ form.as_p }}  
        <input type="submit" value="Сохранить">  
    </form>  
</body>
</html>

p_library/templates/test_author_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>TESTupdateauth</title>
</head>
<body>
    <form method="post">  
        {% csrf_token %}  
        {{ form.as_p }}  
        <input type="submit" value="Сохранить">  
    </form>  
</body>
</html>